version: "3.8"

services:
  laravel:
    build: 
     args:
      user: dilsonlana
      uid: 1000
     context: ./
     dockerfile: Dockerfile
    image: dilsonlana/laravel-app
    working_dir: /var/www/
    restart: always
    volumes: 
     - ./:/var/www/
    networks:
      - docker-laravel
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel
  redis:
    image: redis:latest
    networks:
      - docker-laravel
  mysql:
    image: amd64/mysql:5.7.36
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/arm64
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel
networks:
  docker-laravel:
    driver: bridge
